export enum EventType {
  Birth = 'BIRTH',
  Death = 'DEATH',
  Predation = 'PREDATION',
  Reproduction = 'REPRODUCTION',
  Extinction = 'EXTINCTION',
  PopulationBoom = 'POPULATION_BOOM',
  PopulationCrash = 'POPULATION_CRASH',
  WeatherChange = 'WEATHER_CHANGE',
  SeasonChange = 'SEASON_CHANGE',
  SpeciesInvasion = 'SPECIES_INVASION',
  EcosystemStable = 'ECOSYSTEM_STABLE',
  EcosystemCollapse = 'ECOSYSTEM_COLLAPSE',
  SimulationStart = 'SIMULATION_START',
  SimulationReset = 'SIMULATION_RESET',
}

export const EVENT_LABELS: Record<EventType, string> = {
  [EventType.Birth]: 'Рождение',
  [EventType.Death]: 'Гибель',
  [EventType.Predation]: 'Хищничество',
  [EventType.Reproduction]: 'Размножение',
  [EventType.Extinction]: 'Вымирание вида',
  [EventType.PopulationBoom]: 'Всплеск популяции',
  [EventType.PopulationCrash]: 'Крах популяции',
  [EventType.WeatherChange]: 'Изменение погоды',
  [EventType.SeasonChange]: 'Смена сезона',
  [EventType.SpeciesInvasion]: 'Вторжение вида',
  [EventType.EcosystemStable]: 'Равновесие',
  [EventType.EcosystemCollapse]: 'Коллапс экосистемы',
  [EventType.SimulationStart]: 'Старт симуляции',
  [EventType.SimulationReset]: 'Сброс симуляции',
}

export const EVENT_COLORS: Record<EventType, string> = {
  [EventType.Birth]: '#66bb6a',
  [EventType.Death]: '#ef5350',
  [EventType.Predation]: '#ff7043',
  [EventType.Reproduction]: '#26a69a',
  [EventType.Extinction]: '#b71c1c',
  [EventType.PopulationBoom]: '#7e57c2',
  [EventType.PopulationCrash]: '#ec407a',
  [EventType.WeatherChange]: '#42a5f5',
  [EventType.SeasonChange]: '#26c6da',
  [EventType.SpeciesInvasion]: '#ab47bc',
  [EventType.EcosystemStable]: '#9ccc65',
  [EventType.EcosystemCollapse]: '#d84315',
  [EventType.SimulationStart]: '#78909c',
  [EventType.SimulationReset]: '#78909c',
}
